name: dataly
description: Helping you manage your data usage in relation with your mobile plan reset date.
version: 1.1.0+10

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.2.0
  shared_preferences: ^0.5.4+6
  intl: ^0.16.0
  font_awesome_flutter: ^8.5.0
  percent_indicator: ^2.1.1+1
  sms_maintained: ^0.2.5
  flutter_share: ^1.0.2+1
  file_picker: ^1.4.3+1
  path_provider: ^1.4.5

flutter:
  uses-material-design: true