name: dataly
description: Helping you manage your data usage in relation with your mobile plan reset date.
version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.1.0+1
  shared_preferences: ^0.5.4+1

  percent_indicator: ^2.1.1+1
  sms_maintained: ^0.2.5

flutter:
  uses-material-design: true